FASTING_FOLLOWUP_LABS = {
    "FBS",
    "Glucose",
    "Triglycerides",
}

INPUT_HEALTH_TERMS = (
    "สุขภาพ",
    "ผลตรวจ",
    "ตรวจเลือด",
    "ค่าเลือด",
    "แลป",
    "แล็บ",
    "lab",
    "ldl",
    "hdl",
    "hba1c",
    "a1c",
    "fbs",
    "glucose",
    "cholesterol",
    "triglyceride",
    "egfr",
    "creatinine",
    "bun",
    "ast",
    "alt",
    "ความดัน",
    "เบาหวาน",
    "ไขมัน",
    "ไต",
    "ตับ",
    "ยา",
    "อาการ",
    "เจ็บ",
    "ปวด",
    "เวียนหัว",
    "หอบ",
    "เหนื่อย",
)

INPUT_NON_HEALTH_TERMS = (
    "เกม",
    "หนัง",
    "ภาพยนตร์",
    "เพลง",
    "ดนตรี",
    "การเมือง",
    "ข่าว",
    "กีฬา",
    "ฟุตบอล",
    "เขียนโค้ด",
    "โค้ด",
    "python",
    "javascript",
    "ท่องเที่ยว",
    "เที่ยว",
    "ร้านอาหาร",
    "ช้อป",
    "shopping",
    "หุ้น",
    "คริปโต",
    "game",
    "movie",
    "music",
    "politics",
    "football",
    "sport",
    "code",
    "travel",
    "restaurant",
    "stock",
    "crypto",
)

OUTPUT_REVIEW_INTENTS = {"medication_safety", "urgent_red_flag"}

OUTPUT_REVIEW_PATTERNS = (
    r"หยุดยา",
    r"ปรับยา",
    r"เพิ่มยา",
    r"ลดยา",
    r"เริ่มยา",
    r"ขนาดยา",
    r"(?:กิน|รับประทาน).{0,20}\d+(?:\.\d+)?\s*(?:mg|มก\.?|มิลลิกรัม)",
    r"เป็น(?:โรค)?[ก-ฮa-zA-Z]+แน่นอน",
    r"วินิจฉัยว่า",
    r"ฟันธง",
    r"อันตราย",
    r"วิกฤต",
    r"ร้ายแรง",
)
